version: "3.8"

services:
  app:
    build: .
    container_name: my_project
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - ENV=production
    command: python main.py
